version: '3'

services:

  # nginx-front:
  #   image: nginx:latest
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./nginx/angular.conf:/etc/nginx/conf.d/default.conf

  # angular:
  #   build: front-end
  #   volumes:
  #     - "./front-end:/app"

  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./nginx.conf:/etc/conf.d/default.conf
      - ./:/app

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=shop"
    volumes:
      - ./:/app

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - ${POSTGRES_PORTS:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-coins}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      # POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${POSTGRES_USER:-root}
      PGDATA: /var/lib/postgresql/data/secondary_folder/
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

# volumes:
###> doctrine/doctrine-bundle ###
  # db-data:
###< doctrine/doctrine-bundle ###
